<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260216002750 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE time_slots (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_available BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, coach_id INT NOT NULL, booked_by_id INT DEFAULT NULL, coaching_request_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D06D4AC3C105691 ON time_slots (coach_id)');
        $this->addSql('CREATE INDEX IDX_8D06D4ACF4A5BD90 ON time_slots (booked_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D06D4ACAAFD4FAF ON time_slots (coaching_request_id)');
        $this->addSql('ALTER TABLE time_slots ADD CONSTRAINT FK_8D06D4AC3C105691 FOREIGN KEY (coach_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE time_slots ADD CONSTRAINT FK_8D06D4ACF4A5BD90 FOREIGN KEY (booked_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE time_slots ADD CONSTRAINT FK_8D06D4ACAAFD4FAF FOREIGN KEY (coaching_request_id) REFERENCES coaching_request (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coaching_request ADD time_slot_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE coaching_request ADD CONSTRAINT FK_9079F7FFD62B0FA FOREIGN KEY (time_slot_id) REFERENCES time_slots (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_9079F7FFD62B0FA ON coaching_request (time_slot_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE time_slots DROP CONSTRAINT FK_8D06D4AC3C105691');
        $this->addSql('ALTER TABLE time_slots DROP CONSTRAINT FK_8D06D4ACF4A5BD90');
        $this->addSql('ALTER TABLE time_slots DROP CONSTRAINT FK_8D06D4ACAAFD4FAF');
        $this->addSql('DROP TABLE time_slots');
        $this->addSql('ALTER TABLE coaching_request DROP CONSTRAINT FK_9079F7FFD62B0FA');
        $this->addSql('DROP INDEX IDX_9079F7FFD62B0FA');
        $this->addSql('ALTER TABLE coaching_request DROP time_slot_id');
    }
}
