<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260304180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Safe forward sync: add missing activity/goal/routine/message columns, daily_activity_log table, and align chatroom/goal_participation columns.';
    }

    public function up(Schema $schema): void
    {
        // 1) daily_activity_log (missing in some DBs)
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS daily_activity_log (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                log_date DATE NOT NULL,
                total_activities INT NOT NULL,
                completed_activities INT NOT NULL,
                total_routines INT NOT NULL,
                completed_routines INT NOT NULL,
                completion_percentage NUMERIC(5, 2) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                user_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_70DABD61A76ED395 ON daily_activity_log (user_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_user_date ON daily_activity_log (user_id, log_date)');
        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_70DABD61A76ED395'
                ) THEN
                    ALTER TABLE daily_activity_log
                        ADD CONSTRAINT FK_70DABD61A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE;
                END IF;
            END
            $$;
        SQL);

        // 2) activity columns (add only; never drop)
        $this->addSql('ALTER TABLE activity ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE activity ADD COLUMN IF NOT EXISTS deadline DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE activity ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN NOT NULL DEFAULT false');
        $this->addSql('ALTER TABLE activity ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE activity ADD COLUMN IF NOT EXISTS actual_duration_minutes INT DEFAULT NULL');
        $this->addSql('ALTER TABLE activity ADD COLUMN IF NOT EXISTS planned_duration_minutes INT DEFAULT NULL');

        // 3) goal columns
        $this->addSql('ALTER TABLE goal ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE goal ADD COLUMN IF NOT EXISTS deadline DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE goal ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN NOT NULL DEFAULT false');
        $this->addSql('ALTER TABLE goal ADD COLUMN IF NOT EXISTS progress INT DEFAULT 0');
        $this->addSql('ALTER TABLE goal ADD COLUMN IF NOT EXISTS required_tasks INT DEFAULT NULL');
        $this->addSql('ALTER TABLE goal ADD COLUMN IF NOT EXISTS trello_board_id VARCHAR(255) DEFAULT NULL');

        // 4) routine columns
        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'routine' AND column_name = 'status'
                ) THEN
                    ALTER TABLE routine ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'draft';
                END IF;
            END
            $$;
        SQL);
        $this->addSql('ALTER TABLE routine ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE routine ADD COLUMN IF NOT EXISTS deadline DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE routine ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN NOT NULL DEFAULT false');

        // 5) message.author_id (entity requires NOT NULL); backfill only if rows exist
        $this->addSql(<<<'SQL'
            DO $$
            DECLARE
                v_user_id INT;
                v_count BIGINT;
            BEGIN
                -- Add column as nullable first to allow backfill
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'message' AND column_name = 'author_id'
                ) THEN
                    ALTER TABLE message ADD COLUMN author_id INT DEFAULT NULL;
                END IF;

                SELECT COUNT(*) INTO v_count FROM message;
                IF v_count > 0 THEN
                    SELECT MIN(id) INTO v_user_id FROM "user";
                    IF v_user_id IS NULL THEN
                        RAISE EXCEPTION 'Cannot backfill message.author_id because "user" table is empty.';
                    END IF;
                    UPDATE message SET author_id = v_user_id WHERE author_id IS NULL;
                END IF;

                -- Enforce NOT NULL if the column exists
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'message' AND column_name = 'author_id'
                ) THEN
                    ALTER TABLE message ALTER COLUMN author_id SET NOT NULL;
                END IF;

                -- Add FK + index if missing
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_B6BD307FF675F31B') THEN
                    ALTER TABLE message
                        ADD CONSTRAINT FK_B6BD307FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'IDX_B6BD307FF675F31B') THEN
                    CREATE INDEX IDX_B6BD307FF675F31B ON message (author_id);
                END IF;
            END
            $$;
        SQL);

        // 6) chatroom: align timestamp column name with entity (chatroom.chatroom -> created_at), keep extra columns (e.g. no)
        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'chatroom' AND column_name = 'chatroom'
                )
                AND NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'chatroom' AND column_name = 'created_at'
                ) THEN
                    ALTER TABLE chatroom RENAME COLUMN chatroom TO created_at;
                END IF;
            END
            $$;
        SQL);

        // 7) goal_participation: align FK column names with entity (user_id_id -> user_id, goal_id_id -> goal_id)
        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'goal_participation' AND column_name = 'user_id_id'
                )
                AND NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'goal_participation' AND column_name = 'user_id'
                ) THEN
                    ALTER TABLE goal_participation RENAME COLUMN user_id_id TO user_id;
                END IF;

                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'goal_participation' AND column_name = 'goal_id_id'
                )
                AND NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'goal_participation' AND column_name = 'goal_id'
                ) THEN
                    ALTER TABLE goal_participation RENAME COLUMN goal_id_id TO goal_id;
                END IF;
            END
            $$;
        SQL);
    }

    public function down(Schema $schema): void
    {
        // Best-effort rollback (may drop data). Use only in development.
        $this->addSql('ALTER TABLE daily_activity_log DROP CONSTRAINT IF EXISTS FK_70DABD61A76ED395');
        $this->addSql('DROP TABLE IF EXISTS daily_activity_log');

        $this->addSql('ALTER TABLE activity DROP COLUMN IF EXISTS priority');
        $this->addSql('ALTER TABLE activity DROP COLUMN IF EXISTS deadline');
        $this->addSql('ALTER TABLE activity DROP COLUMN IF EXISTS is_favorite');
        $this->addSql('ALTER TABLE activity DROP COLUMN IF EXISTS completed_at');
        $this->addSql('ALTER TABLE activity DROP COLUMN IF EXISTS actual_duration_minutes');
        $this->addSql('ALTER TABLE activity DROP COLUMN IF EXISTS planned_duration_minutes');

        $this->addSql('ALTER TABLE goal DROP COLUMN IF EXISTS priority');
        $this->addSql('ALTER TABLE goal DROP COLUMN IF EXISTS deadline');
        $this->addSql('ALTER TABLE goal DROP COLUMN IF EXISTS is_favorite');
        $this->addSql('ALTER TABLE goal DROP COLUMN IF EXISTS progress');
        $this->addSql('ALTER TABLE goal DROP COLUMN IF EXISTS required_tasks');
        $this->addSql('ALTER TABLE goal DROP COLUMN IF EXISTS trello_board_id');

        $this->addSql('ALTER TABLE routine DROP COLUMN IF EXISTS status');
        $this->addSql('ALTER TABLE routine DROP COLUMN IF EXISTS priority');
        $this->addSql('ALTER TABLE routine DROP COLUMN IF EXISTS deadline');
        $this->addSql('ALTER TABLE routine DROP COLUMN IF EXISTS is_favorite');

        $this->addSql('ALTER TABLE message DROP CONSTRAINT IF EXISTS FK_B6BD307FF675F31B');
        $this->addSql('DROP INDEX IF EXISTS IDX_B6BD307FF675F31B');
        $this->addSql('ALTER TABLE message DROP COLUMN IF EXISTS author_id');

        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'chatroom' AND column_name = 'created_at'
                )
                AND NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'chatroom' AND column_name = 'chatroom'
                ) THEN
                    ALTER TABLE chatroom RENAME COLUMN created_at TO chatroom;
                END IF;
            END
            $$;
        SQL);

        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'goal_participation' AND column_name = 'user_id'
                )
                AND NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'goal_participation' AND column_name = 'user_id_id'
                ) THEN
                    ALTER TABLE goal_participation RENAME COLUMN user_id TO user_id_id;
                END IF;

                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'goal_participation' AND column_name = 'goal_id'
                )
                AND NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'goal_participation' AND column_name = 'goal_id_id'
                ) THEN
                    ALTER TABLE goal_participation RENAME COLUMN goal_id TO goal_id_id;
                END IF;
            END
            $$;
        SQL);
    }
}

