<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260220224340 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE message_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reason VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, review_note TEXT DEFAULT NULL, message_id INT NOT NULL, reporter_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F308EA8B537A1329 ON message_report (message_id)');
        $this->addSql('CREATE INDEX IDX_F308EA8BE1CFE6F5 ON message_report (reporter_id)');
        $this->addSql('CREATE INDEX IDX_F308EA8BFC6B21F1 ON message_report (reviewed_by_id)');
        $this->addSql('ALTER TABLE message_report ADD CONSTRAINT FK_F308EA8B537A1329 FOREIGN KEY (message_id) REFERENCES message (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_report ADD CONSTRAINT FK_F308EA8BE1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_report ADD CONSTRAINT FK_F308EA8BFC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE message_report DROP CONSTRAINT FK_F308EA8B537A1329');
        $this->addSql('ALTER TABLE message_report DROP CONSTRAINT FK_F308EA8BE1CFE6F5');
        $this->addSql('ALTER TABLE message_report DROP CONSTRAINT FK_F308EA8BFC6B21F1');
        $this->addSql('DROP TABLE message_report');
    }
}
