<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Add suggestion table and user preferred_language (from pi_ranim features).
 */
final class Version20260225100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add suggestion table for AI suggestions and user preferred_language for i18n';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE suggestion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(50) DEFAULT NULL, is_read BOOLEAN NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DD80F31BA76ED395 ON suggestion (user_id)');
        $this->addSql('ALTER TABLE suggestion ADD CONSTRAINT FK_DD80F31BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');

        if (!$schema->getTable('user')->hasColumn('preferred_language')) {
            $this->addSql('ALTER TABLE "user" ADD preferred_language VARCHAR(10) DEFAULT NULL');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE suggestion DROP CONSTRAINT FK_DD80F31BA76ED395');
        $this->addSql('DROP TABLE suggestion');
        if ($schema->getTable('user')->hasColumn('preferred_language')) {
            $this->addSql('ALTER TABLE "user" DROP preferred_language');
        }
    }
}
