<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260212032942 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration TIME(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, has_reminder BOOLEAN NOT NULL, reminder_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, routine_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC74095AF27A94C7 ON activity (routine_id)');
        $this->addSql('CREATE TABLE coaching_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, coach_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9079F7FFA76ED395 ON coaching_request (user_id)');
        $this->addSql('CREATE INDEX IDX_9079F7FF3C105691 ON coaching_request (coach_id)');
        $this->addSql('CREATE TABLE routine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, visibility VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, goal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4BF6D8D6667D1AFE ON routine (goal_id)');
        $this->addSql('CREATE TABLE "session" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(30) NOT NULL, proposed_time_by_user TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, proposed_time_by_coach TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, coaching_request_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D044D5D4AAFD4FAF ON "session" (coaching_request_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AF27A94C7 FOREIGN KEY (routine_id) REFERENCES routine (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coaching_request ADD CONSTRAINT FK_9079F7FFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coaching_request ADD CONSTRAINT FK_9079F7FF3C105691 FOREIGN KEY (coach_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE routine ADD CONSTRAINT FK_4BF6D8D6667D1AFE FOREIGN KEY (goal_id) REFERENCES goal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "session" ADD CONSTRAINT FK_D044D5D4AAFD4FAF FOREIGN KEY (coaching_request_id) REFERENCES coaching_request (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095AF27A94C7');
        $this->addSql('ALTER TABLE coaching_request DROP CONSTRAINT FK_9079F7FFA76ED395');
        $this->addSql('ALTER TABLE coaching_request DROP CONSTRAINT FK_9079F7FF3C105691');
        $this->addSql('ALTER TABLE routine DROP CONSTRAINT FK_4BF6D8D6667D1AFE');
        $this->addSql('ALTER TABLE "session" DROP CONSTRAINT FK_D044D5D4AAFD4FAF');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE coaching_request');
        $this->addSql('DROP TABLE routine');
        $this->addSql('DROP TABLE "session"');
    }
}
