<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222015353 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_login_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_address VARCHAR(45) NOT NULL, user_agent VARCHAR(500) NOT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_suspicious BOOLEAN NOT NULL, location VARCHAR(100) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D919C366A76ED395 ON user_login_history (user_id)');
        $this->addSql('CREATE INDEX idx_logged_at ON user_login_history (logged_at)');
        $this->addSql('CREATE INDEX idx_ip_address ON user_login_history (ip_address)');
        $this->addSql('ALTER TABLE user_login_history ADD CONSTRAINT FK_D919C366A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_login_history DROP CONSTRAINT FK_D919C366A76ED395');
        $this->addSql('DROP TABLE user_login_history');
    }
}
