<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260216181812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE message_read_receipt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B7FE12F537A1329 ON message_read_receipt (message_id)');
        $this->addSql('CREATE INDEX IDX_2B7FE12FA76ED395 ON message_read_receipt (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_read ON message_read_receipt (message_id, user_id)');
        $this->addSql('ALTER TABLE message_read_receipt ADD CONSTRAINT FK_2B7FE12F537A1329 FOREIGN KEY (message_id) REFERENCES message (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_read_receipt ADD CONSTRAINT FK_2B7FE12FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE message_read_receipt DROP CONSTRAINT FK_2B7FE12F537A1329');
        $this->addSql('ALTER TABLE message_read_receipt DROP CONSTRAINT FK_2B7FE12FA76ED395');
        $this->addSql('DROP TABLE message_read_receipt');
    }
}
