<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260225164234 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE realtime_notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(40) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recipient_id INT NOT NULL, related_post_id INT DEFAULT NULL, related_comment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CDB90038E92F8F78 ON realtime_notifications (recipient_id)');
        $this->addSql('CREATE INDEX IDX_CDB900387490C989 ON realtime_notifications (related_post_id)');
        $this->addSql('CREATE INDEX IDX_CDB9003872A475A3 ON realtime_notifications (related_comment_id)');
        $this->addSql('CREATE INDEX idx_rt_notification_recipient_read ON realtime_notifications (recipient_id, is_read, created_at)');
        $this->addSql('ALTER TABLE realtime_notifications ADD CONSTRAINT FK_CDB90038E92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE realtime_notifications ADD CONSTRAINT FK_CDB900387490C989 FOREIGN KEY (related_post_id) REFERENCES post (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE realtime_notifications ADD CONSTRAINT FK_CDB9003872A475A3 FOREIGN KEY (related_comment_id) REFERENCES comment (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE realtime_notifications DROP CONSTRAINT FK_CDB90038E92F8F78');
        $this->addSql('ALTER TABLE realtime_notifications DROP CONSTRAINT FK_CDB900387490C989');
        $this->addSql('ALTER TABLE realtime_notifications DROP CONSTRAINT FK_CDB9003872A475A3');
        $this->addSql('DROP TABLE realtime_notifications');
    }
}
