<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260226031225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chatroom (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, state VARCHAR(50) NOT NULL, goal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F3E6EC4667D1AFE ON chatroom (goal_id)');
        $this->addSql('CREATE TABLE fcm_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, device VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_19B88AF95F37A13B ON fcm_token (token)');
        $this->addSql('CREATE INDEX idx_fcm_token_user ON fcm_token (user_id)');
        $this->addSql('CREATE INDEX idx_fcm_token_token ON fcm_token (token)');
        $this->addSql('CREATE TABLE goal_participation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, role VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, user_id INT NOT NULL, goal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_91C54215A76ED395 ON goal_participation (user_id)');
        $this->addSql('CREATE INDEX IDX_91C54215667D1AFE ON goal_participation (goal_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_pinned BOOLEAN DEFAULT false NOT NULL, is_edited BOOLEAN DEFAULT false NOT NULL, edited_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, translated_content TEXT DEFAULT NULL, translated_language VARCHAR(10) DEFAULT NULL, attachment_path VARCHAR(255) DEFAULT NULL, attachment_type VARCHAR(50) DEFAULT NULL, attachment_original_name VARCHAR(255) DEFAULT NULL, audio_duration INT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, file_name VARCHAR(255) DEFAULT NULL, file_size INT DEFAULT NULL, file_type VARCHAR(100) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_toxic BOOLEAN DEFAULT false NOT NULL, is_spam BOOLEAN DEFAULT false NOT NULL, moderation_status VARCHAR(20) DEFAULT \'approved\' NOT NULL, toxicity_score DOUBLE PRECISION DEFAULT NULL, spam_score DOUBLE PRECISION DEFAULT NULL, moderation_reason TEXT DEFAULT NULL, chatroom_id INT DEFAULT NULL, private_chatroom_id INT DEFAULT NULL, author_id INT NOT NULL, reply_to_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307FCAF8A031 ON message (chatroom_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307F4948104 ON message (private_chatroom_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FF675F31B ON message (author_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FFFDF7169 ON message (reply_to_id)');
        $this->addSql('CREATE TABLE message_reaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reaction_type VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ADF1C3E6537A1329 ON message_reaction (message_id)');
        $this->addSql('CREATE INDEX IDX_ADF1C3E6A76ED395 ON message_reaction (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_message_reaction ON message_reaction (message_id, user_id, reaction_type)');
        $this->addSql('CREATE TABLE message_read_receipt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B7FE12F537A1329 ON message_read_receipt (message_id)');
        $this->addSql('CREATE INDEX IDX_2B7FE12FA76ED395 ON message_read_receipt (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_message_user_read ON message_read_receipt (message_id, user_id)');
        $this->addSql('CREATE TABLE message_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reason VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, review_note TEXT DEFAULT NULL, message_id INT NOT NULL, reporter_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F308EA8B537A1329 ON message_report (message_id)');
        $this->addSql('CREATE INDEX IDX_F308EA8BE1CFE6F5 ON message_report (reporter_id)');
        $this->addSql('CREATE INDEX IDX_F308EA8BFC6B21F1 ON message_report (reviewed_by_id)');
        $this->addSql('CREATE TABLE message_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_language VARCHAR(10) NOT NULL, target_language VARCHAR(10) NOT NULL, translated_text TEXT NOT NULL, provider VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usage_count INT DEFAULT 1 NOT NULL, message_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D4161B96537A1329 ON message_translation (message_id)');
        $this->addSql('CREATE INDEX idx_message_lang ON message_translation (message_id, target_language)');
        $this->addSql('CREATE INDEX idx_created_at ON message_translation (created_at)');
        $this->addSql('CREATE TABLE private_chatroom (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, parent_goal_id INT NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B8A8B16914356EB8 ON private_chatroom (parent_goal_id)');
        $this->addSql('CREATE INDEX IDX_B8A8B16961220EA6 ON private_chatroom (creator_id)');
        $this->addSql('CREATE TABLE private_chatroom_members (private_chatroom_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (private_chatroom_id, user_id))');
        $this->addSql('CREATE INDEX IDX_ADB61C504948104 ON private_chatroom_members (private_chatroom_id)');
        $this->addSql('CREATE INDEX IDX_ADB61C50A76ED395 ON private_chatroom_members (user_id)');
        $this->addSql('CREATE TABLE user_presence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_typing BOOLEAN DEFAULT false NOT NULL, typing_in_chatroom_id INT DEFAULT NULL, typing_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_89FA23A5A76ED395 ON user_presence (user_id)');
        $this->addSql('ALTER TABLE chatroom ADD CONSTRAINT FK_1F3E6EC4667D1AFE FOREIGN KEY (goal_id) REFERENCES goal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fcm_token ADD CONSTRAINT FK_19B88AF9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal_participation ADD CONSTRAINT FK_91C54215A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal_participation ADD CONSTRAINT FK_91C54215667D1AFE FOREIGN KEY (goal_id) REFERENCES goal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FCAF8A031 FOREIGN KEY (chatroom_id) REFERENCES chatroom (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F4948104 FOREIGN KEY (private_chatroom_id) REFERENCES private_chatroom (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FFFDF7169 FOREIGN KEY (reply_to_id) REFERENCES message (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_reaction ADD CONSTRAINT FK_ADF1C3E6537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_reaction ADD CONSTRAINT FK_ADF1C3E6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_read_receipt ADD CONSTRAINT FK_2B7FE12F537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_read_receipt ADD CONSTRAINT FK_2B7FE12FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_report ADD CONSTRAINT FK_F308EA8B537A1329 FOREIGN KEY (message_id) REFERENCES message (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_report ADD CONSTRAINT FK_F308EA8BE1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_report ADD CONSTRAINT FK_F308EA8BFC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_translation ADD CONSTRAINT FK_D4161B96537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE private_chatroom ADD CONSTRAINT FK_B8A8B16914356EB8 FOREIGN KEY (parent_goal_id) REFERENCES goal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE private_chatroom ADD CONSTRAINT FK_B8A8B16961220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE private_chatroom_members ADD CONSTRAINT FK_ADB61C504948104 FOREIGN KEY (private_chatroom_id) REFERENCES private_chatroom (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE private_chatroom_members ADD CONSTRAINT FK_ADB61C50A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_presence ADD CONSTRAINT FK_89FA23A5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT fk_6d28840d613fecdf');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT fk_6d28840da76ed395');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT fk_65d29b32613fecdf');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT fk_65d29b32a76ed395');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE payments');
        $this->addSql('ALTER TABLE goal DROP title');
        $this->addSql('ALTER TABLE "user" ADD profile_picture_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD profile_picture_size INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount DOUBLE PRECISION NOT NULL, status VARCHAR(20) NOT NULL, payment_method VARCHAR(30) NOT NULL, transaction_id VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, user_id INT NOT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_6d28840da76ed395 ON payment (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_6d28840d613fecdf ON payment (session_id)');
        $this->addSql('CREATE TABLE payments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, status VARCHAR(20) NOT NULL, payment_method VARCHAR(50) DEFAULT NULL, transaction_id VARCHAR(255) DEFAULT NULL, payment_data TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, session_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_65d29b32a76ed395 ON payments (user_id)');
        $this->addSql('CREATE INDEX idx_65d29b32613fecdf ON payments (session_id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT fk_6d28840d613fecdf FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT fk_6d28840da76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT fk_65d29b32613fecdf FOREIGN KEY (session_id) REFERENCES session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT fk_65d29b32a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chatroom DROP CONSTRAINT FK_1F3E6EC4667D1AFE');
        $this->addSql('ALTER TABLE fcm_token DROP CONSTRAINT FK_19B88AF9A76ED395');
        $this->addSql('ALTER TABLE goal_participation DROP CONSTRAINT FK_91C54215A76ED395');
        $this->addSql('ALTER TABLE goal_participation DROP CONSTRAINT FK_91C54215667D1AFE');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FCAF8A031');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F4948104');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF675F31B');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FFFDF7169');
        $this->addSql('ALTER TABLE message_reaction DROP CONSTRAINT FK_ADF1C3E6537A1329');
        $this->addSql('ALTER TABLE message_reaction DROP CONSTRAINT FK_ADF1C3E6A76ED395');
        $this->addSql('ALTER TABLE message_read_receipt DROP CONSTRAINT FK_2B7FE12F537A1329');
        $this->addSql('ALTER TABLE message_read_receipt DROP CONSTRAINT FK_2B7FE12FA76ED395');
        $this->addSql('ALTER TABLE message_report DROP CONSTRAINT FK_F308EA8B537A1329');
        $this->addSql('ALTER TABLE message_report DROP CONSTRAINT FK_F308EA8BE1CFE6F5');
        $this->addSql('ALTER TABLE message_report DROP CONSTRAINT FK_F308EA8BFC6B21F1');
        $this->addSql('ALTER TABLE message_translation DROP CONSTRAINT FK_D4161B96537A1329');
        $this->addSql('ALTER TABLE private_chatroom DROP CONSTRAINT FK_B8A8B16914356EB8');
        $this->addSql('ALTER TABLE private_chatroom DROP CONSTRAINT FK_B8A8B16961220EA6');
        $this->addSql('ALTER TABLE private_chatroom_members DROP CONSTRAINT FK_ADB61C504948104');
        $this->addSql('ALTER TABLE private_chatroom_members DROP CONSTRAINT FK_ADB61C50A76ED395');
        $this->addSql('ALTER TABLE user_presence DROP CONSTRAINT FK_89FA23A5A76ED395');
        $this->addSql('DROP TABLE chatroom');
        $this->addSql('DROP TABLE fcm_token');
        $this->addSql('DROP TABLE goal_participation');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE message_reaction');
        $this->addSql('DROP TABLE message_read_receipt');
        $this->addSql('DROP TABLE message_report');
        $this->addSql('DROP TABLE message_translation');
        $this->addSql('DROP TABLE private_chatroom');
        $this->addSql('DROP TABLE private_chatroom_members');
        $this->addSql('DROP TABLE user_presence');
        $this->addSql('ALTER TABLE goal ADD title VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE "user" DROP profile_picture_name');
        $this->addSql('ALTER TABLE "user" DROP profile_picture_size');
    }
}
