<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260220222450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE private_chatroom (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, parent_goal_id INT NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B8A8B16914356EB8 ON private_chatroom (parent_goal_id)');
        $this->addSql('CREATE INDEX IDX_B8A8B16961220EA6 ON private_chatroom (creator_id)');
        $this->addSql('CREATE TABLE private_chatroom_members (private_chatroom_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (private_chatroom_id, user_id))');
        $this->addSql('CREATE INDEX IDX_ADB61C504948104 ON private_chatroom_members (private_chatroom_id)');
        $this->addSql('CREATE INDEX IDX_ADB61C50A76ED395 ON private_chatroom_members (user_id)');
        $this->addSql('ALTER TABLE private_chatroom ADD CONSTRAINT FK_B8A8B16914356EB8 FOREIGN KEY (parent_goal_id) REFERENCES goal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE private_chatroom ADD CONSTRAINT FK_B8A8B16961220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE private_chatroom_members ADD CONSTRAINT FK_ADB61C504948104 FOREIGN KEY (private_chatroom_id) REFERENCES private_chatroom (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE private_chatroom_members ADD CONSTRAINT FK_ADB61C50A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD private_chatroom_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE message ALTER chatroom_id DROP NOT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F4948104 FOREIGN KEY (private_chatroom_id) REFERENCES private_chatroom (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_B6BD307F4948104 ON message (private_chatroom_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE private_chatroom DROP CONSTRAINT FK_B8A8B16914356EB8');
        $this->addSql('ALTER TABLE private_chatroom DROP CONSTRAINT FK_B8A8B16961220EA6');
        $this->addSql('ALTER TABLE private_chatroom_members DROP CONSTRAINT FK_ADB61C504948104');
        $this->addSql('ALTER TABLE private_chatroom_members DROP CONSTRAINT FK_ADB61C50A76ED395');
        $this->addSql('DROP TABLE private_chatroom');
        $this->addSql('DROP TABLE private_chatroom_members');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F4948104');
        $this->addSql('DROP INDEX IDX_B6BD307F4948104');
        $this->addSql('ALTER TABLE message DROP private_chatroom_id');
        $this->addSql('ALTER TABLE message ALTER chatroom_id SET NOT NULL');
    }
}
