<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260211152606 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE goal_participation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, goal_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_91C542159D86650F ON goal_participation (user_id_id)');
        $this->addSql('CREATE INDEX IDX_91C5421547826CD6 ON goal_participation (goal_id_id)');
        $this->addSql('ALTER TABLE goal_participation ADD CONSTRAINT FK_91C542159D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal_participation ADD CONSTRAINT FK_91C5421547826CD6 FOREIGN KEY (goal_id_id) REFERENCES goal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chatroom ADD goal_id INT NOT NULL');
        $this->addSql('ALTER TABLE chatroom ADD CONSTRAINT FK_1F3E6EC4667D1AFE FOREIGN KEY (goal_id) REFERENCES goal (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F3E6EC4667D1AFE ON chatroom (goal_id)');
        $this->addSql('ALTER TABLE message ADD chatroom_id INT NOT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FCAF8A031 FOREIGN KEY (chatroom_id) REFERENCES chatroom (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_B6BD307FCAF8A031 ON message (chatroom_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE goal_participation DROP CONSTRAINT FK_91C542159D86650F');
        $this->addSql('ALTER TABLE goal_participation DROP CONSTRAINT FK_91C5421547826CD6');
        $this->addSql('DROP TABLE goal_participation');
        $this->addSql('ALTER TABLE chatroom DROP CONSTRAINT FK_1F3E6EC4667D1AFE');
        $this->addSql('DROP INDEX UNIQ_1F3E6EC4667D1AFE');
        $this->addSql('ALTER TABLE chatroom DROP goal_id');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FCAF8A031');
        $this->addSql('DROP INDEX IDX_B6BD307FCAF8A031');
        $this->addSql('ALTER TABLE message DROP chatroom_id');
    }
}
