<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260225135023 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE message_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_language VARCHAR(10) NOT NULL, target_language VARCHAR(10) NOT NULL, translated_text TEXT NOT NULL, provider VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, usage_count INT DEFAULT 1 NOT NULL, message_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D4161B96537A1329 ON message_translation (message_id)');
        $this->addSql('CREATE INDEX idx_message_lang ON message_translation (message_id, target_language)');
        $this->addSql('CREATE INDEX idx_created_at ON message_translation (created_at)');
        $this->addSql('ALTER TABLE message_translation ADD CONSTRAINT FK_D4161B96537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE message_translation DROP CONSTRAINT FK_D4161B96537A1329');
        $this->addSql('DROP TABLE message_translation');
    }
}
