<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260218160959 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration TIME(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, has_reminder BOOLEAN NOT NULL, reminder_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, routine_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC74095AF27A94C7 ON activity (routine_id)');
        $this->addSql('CREATE TABLE coaching_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, goal VARCHAR(100) DEFAULT NULL, level VARCHAR(50) DEFAULT NULL, frequency VARCHAR(50) DEFAULT NULL, budget DOUBLE PRECISION DEFAULT NULL, coaching_type VARCHAR(50) DEFAULT NULL, priority VARCHAR(20) NOT NULL, user_id INT NOT NULL, coach_id INT NOT NULL, time_slot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9079F7FFA76ED395 ON coaching_request (user_id)');
        $this->addSql('CREATE INDEX IDX_9079F7FF3C105691 ON coaching_request (coach_id)');
        $this->addSql('CREATE INDEX IDX_9079F7FFD62B0FA ON coaching_request (time_slot_id)');
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id INT NOT NULL, commenter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526C4B89032C ON comment (post_id)');
        $this->addSql('CREATE INDEX IDX_9474526CB4D5A9E2 ON comment (commenter_id)');
        $this->addSql('CREATE TABLE goal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FCDCEB2EA76ED395 ON goal (user_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, coaching_request_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE INDEX IDX_6000B0D3AAFD4FAF ON notifications (coaching_request_id)');
        $this->addSql('CREATE TABLE post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DB03A8386 ON post (created_by_id)');
        $this->addSql('CREATE TABLE post_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, post_id INT NOT NULL, liker_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_653627B84B89032C ON post_like (post_id)');
        $this->addSql('CREATE INDEX IDX_653627B8979F103A ON post_like (liker_id)');
        $this->addSql('CREATE TABLE reclamation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CE606404A76ED395 ON reclamation (user_id)');
        $this->addSql('CREATE TABLE response (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reclamation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3E7B0BFB2D6BA2D9 ON response (reclamation_id)');
        $this->addSql('CREATE TABLE reviews (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating DOUBLE PRECISION NOT NULL, comment TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_visible BOOLEAN DEFAULT true NOT NULL, is_verified BOOLEAN DEFAULT false NOT NULL, user_id INT NOT NULL, coach_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6970EB0FA76ED395 ON reviews (user_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0F3C105691 ON reviews (coach_id)');
        $this->addSql('CREATE TABLE routine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, visibility VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, goal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4BF6D8D6667D1AFE ON routine (goal_id)');
        $this->addSql('CREATE TABLE "session" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(30) NOT NULL, proposed_time_by_user TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, proposed_time_by_coach TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, coaching_request_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D044D5D4AAFD4FAF ON "session" (coaching_request_id)');
        $this->addSql('CREATE TABLE time_slots (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_available BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, coach_id INT NOT NULL, booked_by_id INT DEFAULT NULL, coaching_request_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D06D4AC3C105691 ON time_slots (coach_id)');
        $this->addSql('CREATE INDEX IDX_8D06D4ACF4A5BD90 ON time_slots (booked_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D06D4ACAAFD4FAF ON time_slots (coaching_request_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(200) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, phone_number VARCHAR(20) DEFAULT NULL, age INT DEFAULT NULL, status VARCHAR(20) NOT NULL, speciality VARCHAR(200) DEFAULT NULL, availability VARCHAR(200) DEFAULT NULL, rating DOUBLE PRECISION DEFAULT NULL, review_count INT DEFAULT NULL, price_per_session DOUBLE PRECISION DEFAULT NULL, bio VARCHAR(500) DEFAULT NULL, photo_url VARCHAR(255) DEFAULT NULL, badges JSON DEFAULT NULL, responds_quickly BOOLEAN DEFAULT NULL, total_sessions INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AF27A94C7 FOREIGN KEY (routine_id) REFERENCES routine (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coaching_request ADD CONSTRAINT FK_9079F7FFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coaching_request ADD CONSTRAINT FK_9079F7FF3C105691 FOREIGN KEY (coach_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE coaching_request ADD CONSTRAINT FK_9079F7FFD62B0FA FOREIGN KEY (time_slot_id) REFERENCES time_slots (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C4B89032C FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CB4D5A9E2 FOREIGN KEY (commenter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3AAFD4FAF FOREIGN KEY (coaching_request_id) REFERENCES coaching_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_like ADD CONSTRAINT FK_653627B84B89032C FOREIGN KEY (post_id) REFERENCES post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_like ADD CONSTRAINT FK_653627B8979F103A FOREIGN KEY (liker_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE606404A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE response ADD CONSTRAINT FK_3E7B0BFB2D6BA2D9 FOREIGN KEY (reclamation_id) REFERENCES reclamation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F3C105691 FOREIGN KEY (coach_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE routine ADD CONSTRAINT FK_4BF6D8D6667D1AFE FOREIGN KEY (goal_id) REFERENCES goal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "session" ADD CONSTRAINT FK_D044D5D4AAFD4FAF FOREIGN KEY (coaching_request_id) REFERENCES coaching_request (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE time_slots ADD CONSTRAINT FK_8D06D4AC3C105691 FOREIGN KEY (coach_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE time_slots ADD CONSTRAINT FK_8D06D4ACF4A5BD90 FOREIGN KEY (booked_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE time_slots ADD CONSTRAINT FK_8D06D4ACAAFD4FAF FOREIGN KEY (coaching_request_id) REFERENCES coaching_request (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095AF27A94C7');
        $this->addSql('ALTER TABLE coaching_request DROP CONSTRAINT FK_9079F7FFA76ED395');
        $this->addSql('ALTER TABLE coaching_request DROP CONSTRAINT FK_9079F7FF3C105691');
        $this->addSql('ALTER TABLE coaching_request DROP CONSTRAINT FK_9079F7FFD62B0FA');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C4B89032C');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CB4D5A9E2');
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2EA76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3AAFD4FAF');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8DB03A8386');
        $this->addSql('ALTER TABLE post_like DROP CONSTRAINT FK_653627B84B89032C');
        $this->addSql('ALTER TABLE post_like DROP CONSTRAINT FK_653627B8979F103A');
        $this->addSql('ALTER TABLE reclamation DROP CONSTRAINT FK_CE606404A76ED395');
        $this->addSql('ALTER TABLE response DROP CONSTRAINT FK_3E7B0BFB2D6BA2D9');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0FA76ED395');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F3C105691');
        $this->addSql('ALTER TABLE routine DROP CONSTRAINT FK_4BF6D8D6667D1AFE');
        $this->addSql('ALTER TABLE "session" DROP CONSTRAINT FK_D044D5D4AAFD4FAF');
        $this->addSql('ALTER TABLE time_slots DROP CONSTRAINT FK_8D06D4AC3C105691');
        $this->addSql('ALTER TABLE time_slots DROP CONSTRAINT FK_8D06D4ACF4A5BD90');
        $this->addSql('ALTER TABLE time_slots DROP CONSTRAINT FK_8D06D4ACAAFD4FAF');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE coaching_request');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE goal');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE post_like');
        $this->addSql('DROP TABLE reclamation');
        $this->addSql('DROP TABLE response');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE routine');
        $this->addSql('DROP TABLE "session"');
        $this->addSql('DROP TABLE time_slots');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
