<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222142351 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE saved_posts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, saved_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, post_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E58E61E3A76ED395 ON saved_posts (user_id)');
        $this->addSql('CREATE INDEX IDX_E58E61E34B89032C ON saved_posts (post_id)');
        $this->addSql('CREATE UNIQUE INDEX user_post_unique ON saved_posts (user_id, post_id)');
        $this->addSql('ALTER TABLE saved_posts ADD CONSTRAINT FK_E58E61E3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE saved_posts ADD CONSTRAINT FK_E58E61E34B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE saved_posts DROP CONSTRAINT FK_E58E61E3A76ED395');
        $this->addSql('ALTER TABLE saved_posts DROP CONSTRAINT FK_E58E61E34B89032C');
        $this->addSql('DROP TABLE saved_posts');
    }
}
