<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222135931 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_presence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_typing BOOLEAN DEFAULT false NOT NULL, typing_in_chatroom_id INT DEFAULT NULL, typing_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_89FA23A5A76ED395 ON user_presence (user_id)');
        $this->addSql('ALTER TABLE user_presence ADD CONSTRAINT FK_89FA23A5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_read_receipt DROP CONSTRAINT fk_2b7fe12fa76ed395');
        $this->addSql('ALTER TABLE message_read_receipt DROP CONSTRAINT fk_2b7fe12f537a1329');
        $this->addSql('ALTER TABLE message_read_receipt ADD CONSTRAINT FK_2B7FE12FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_read_receipt ADD CONSTRAINT FK_2B7FE12F537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER INDEX unique_read RENAME TO unique_message_user_read');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_presence DROP CONSTRAINT FK_89FA23A5A76ED395');
        $this->addSql('DROP TABLE user_presence');
        $this->addSql('ALTER TABLE message_read_receipt DROP CONSTRAINT FK_2B7FE12F537A1329');
        $this->addSql('ALTER TABLE message_read_receipt DROP CONSTRAINT FK_2B7FE12FA76ED395');
        $this->addSql('ALTER TABLE message_read_receipt ADD CONSTRAINT fk_2b7fe12f537a1329 FOREIGN KEY (message_id) REFERENCES message (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_read_receipt ADD CONSTRAINT fk_2b7fe12fa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX unique_message_user_read RENAME TO unique_read');
    }
}
